/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2020-12-25 12:54:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\"\r\n");
      out.write("\tcontent=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\r\n");
      out.write("<meta name=\"generator\" content=\"Hugo 0.79.0\">\r\n");
      out.write("<title>Album example Â· Bootstrap v5.0</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"canonical\"\r\n");
      out.write("\thref=\"https://getbootstrap.com/docs/5.0/examples/album/\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core CSS -->\r\n");
      out.write("<link href=\"/docs/5.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("\tintegrity=\"sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- Favicons -->\r\n");
      out.write("<link rel=\"apple-touch-icon\"\r\n");
      out.write("\thref=\"/docs/5.0/assets/img/favicons/apple-touch-icon.png\"\r\n");
      out.write("\tsizes=\"180x180\">\r\n");
      out.write("<link rel=\"icon\" href=\"/docs/5.0/assets/img/favicons/favicon-32x32.png\"\r\n");
      out.write("\tsizes=\"32x32\" type=\"image/png\">\r\n");
      out.write("<link rel=\"icon\" href=\"/docs/5.0/assets/img/favicons/favicon-16x16.png\"\r\n");
      out.write("\tsizes=\"16x16\" type=\"image/png\">\r\n");
      out.write("<link rel=\"manifest\" href=\"/docs/5.0/assets/img/favicons/manifest.json\">\r\n");
      out.write("<link rel=\"mask-icon\"\r\n");
      out.write("\thref=\"/docs/5.0/assets/img/favicons/safari-pinned-tab.svg\"\r\n");
      out.write("\tcolor=\"#7952b3\">\r\n");
      out.write("<link rel=\"icon\" href=\"/docs/5.0/assets/img/favicons/favicon.ico\">\r\n");
      out.write("<meta name=\"theme-color\" content=\"#7952b3\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".bd-placeholder-img {\r\n");
      out.write("\tfont-size: 1.125rem;\r\n");
      out.write("\ttext-anchor: middle;\r\n");
      out.write("\t-webkit-user-select: none;\r\n");
      out.write("\t-moz-user-select: none;\r\n");
      out.write("\tuser-select: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( min-width : 768px) {\r\n");
      out.write("\t.bd-placeholder-img-lg {\r\n");
      out.write("\t\tfont-size: 3.5rem;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\t<div class=\"album py-5 bg-light\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card shadow-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t<svg class=\"bd-placeholder-img card-img-top\" width=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\theight=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-label=\"Placeholder: Thumbnail\"\r\n");
      out.write("\t\t\t\t\t\t\t\tpreserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<title>Placeholder</title><rect width=\"100%\" height=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfill=\"#55595c\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text></svg>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"card-text\">This is a wider card with supporting\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttext below as a natural lead-in to additional content. This\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcontent is a little bit longer.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">View</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">Edit</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<small class=\"text-muted\">9 mins</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card shadow-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t<svg class=\"bd-placeholder-img card-img-top\" width=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\theight=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-label=\"Placeholder: Thumbnail\"\r\n");
      out.write("\t\t\t\t\t\t\t\tpreserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<title>Placeholder</title><rect width=\"100%\" height=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfill=\"#55595c\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text></svg>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"card-text\">This is a wider card with supporting\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttext below as a natural lead-in to additional content. This\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcontent is a little bit longer.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">View</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">Edit</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<small class=\"text-muted\">9 mins</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card shadow-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t<svg class=\"bd-placeholder-img card-img-top\" width=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\theight=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-label=\"Placeholder: Thumbnail\"\r\n");
      out.write("\t\t\t\t\t\t\t\tpreserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<title>Placeholder</title><rect width=\"100%\" height=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfill=\"#55595c\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text></svg>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"card-text\">This is a wider card with supporting\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttext below as a natural lead-in to additional content. This\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcontent is a little bit longer.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">View</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">Edit</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<small class=\"text-muted\">9 mins</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card shadow-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t<svg class=\"bd-placeholder-img card-img-top\" width=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\theight=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-label=\"Placeholder: Thumbnail\"\r\n");
      out.write("\t\t\t\t\t\t\t\tpreserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<title>Placeholder</title><rect width=\"100%\" height=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfill=\"#55595c\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text></svg>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"card-text\">This is a wider card with supporting\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttext below as a natural lead-in to additional content. This\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcontent is a little bit longer.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">View</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">Edit</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<small class=\"text-muted\">9 mins</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card shadow-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t<svg class=\"bd-placeholder-img card-img-top\" width=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\theight=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-label=\"Placeholder: Thumbnail\"\r\n");
      out.write("\t\t\t\t\t\t\t\tpreserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<title>Placeholder</title><rect width=\"100%\" height=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfill=\"#55595c\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text></svg>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"card-text\">This is a wider card with supporting\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttext below as a natural lead-in to additional content. This\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcontent is a little bit longer.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">View</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">Edit</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<small class=\"text-muted\">9 mins</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card shadow-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t<svg class=\"bd-placeholder-img card-img-top\" width=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\theight=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-label=\"Placeholder: Thumbnail\"\r\n");
      out.write("\t\t\t\t\t\t\t\tpreserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<title>Placeholder</title><rect width=\"100%\" height=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfill=\"#55595c\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text></svg>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"card-text\">This is a wider card with supporting\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttext below as a natural lead-in to additional content. This\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcontent is a little bit longer.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">View</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">Edit</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<small class=\"text-muted\">9 mins</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card shadow-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t<svg class=\"bd-placeholder-img card-img-top\" width=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\theight=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-label=\"Placeholder: Thumbnail\"\r\n");
      out.write("\t\t\t\t\t\t\t\tpreserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<title>Placeholder</title><rect width=\"100%\" height=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfill=\"#55595c\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text></svg>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"card-text\">This is a wider card with supporting\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttext below as a natural lead-in to additional content. This\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcontent is a little bit longer.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">View</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">Edit</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<small class=\"text-muted\">9 mins</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card shadow-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t<svg class=\"bd-placeholder-img card-img-top\" width=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\theight=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-label=\"Placeholder: Thumbnail\"\r\n");
      out.write("\t\t\t\t\t\t\t\tpreserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<title>Placeholder</title><rect width=\"100%\" height=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfill=\"#55595c\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text></svg>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"card-text\">This is a wider card with supporting\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttext below as a natural lead-in to additional content. This\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcontent is a little bit longer.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">View</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">Edit</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<small class=\"text-muted\">9 mins</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card shadow-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t<svg class=\"bd-placeholder-img card-img-top\" width=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\theight=\"225\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-label=\"Placeholder: Thumbnail\"\r\n");
      out.write("\t\t\t\t\t\t\t\tpreserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<title>Placeholder</title><rect width=\"100%\" height=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfill=\"#55595c\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<text x=\"50%\" y=\"50%\" fill=\"#eceeef\" dy=\".3em\">Thumbnail</text></svg>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"card-text\">This is a wider card with supporting\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttext below as a natural lead-in to additional content. This\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcontent is a little bit longer.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">View</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">Edit</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<small class=\"text-muted\">9 mins</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</main>\r\n");
      out.write("\r\n");
      out.write("\t<footer class=\"text-muted py-5\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<p class=\"float-end mb-1\">\r\n");
      out.write("\t\t\t\t<a href=\"#\">Back to top</a>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p class=\"mb-1\">Album example is &copy; Bootstrap, but please\r\n");
      out.write("\t\t\t\tdownload and customize it for yourself!</p>\r\n");
      out.write("\t\t\t<p class=\"mb-0\">\r\n");
      out.write("\t\t\t\tNew to Bootstrap? <a href=\"/\">Visit the homepage</a> or read our <a\r\n");
      out.write("\t\t\t\t\thref=\"/docs/5.0/getting-started/introduction/\">getting started\r\n");
      out.write("\t\t\t\t\tguide</a>.\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"/docs/5.0/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
